package com.example.cryptoexchangeapp.utils

object DataHelper {
    fun listOfCoins():ArrayList<CoinsID>{
        return arrayListOf(
        CoinsID("Qwsogvtv82FCd","BTC"),
        CoinsID("razxDUgYGNAdQ","ETH"),
        CoinsID("HIVsRcGKkPFtW","USDT"),
        CoinsID("WcwrkfNI4FUAe","BNB"),
        CoinsID("aKzUVe4Hh_CON","USDC"),
        CoinsID("-l8Mn2pVlRs-p","XRP"),
        CoinsID("qzawljRxB5bYu","ADA"),
        CoinsID("a91GCGd_u96cF","DOGE"),
        CoinsID("uW2tk-ILY0ii","MATIC"),
        CoinsID("zNZHO_Sjf","SOL"),
        CoinsID("Mtfb0obXVh59u","WETH"),
        CoinsID("25W7FG7om","DOT"),
        CoinsID("VLqpJwogdhHNb","LINK"),
        CoinsID("qUhEFk1I61atv","TRX"),
        CoinsID("D7B1x_ks7WhV5","LTC"),
        CoinsID("vSo2fu9iE1s0Y","BUSD"),
        CoinsID("xz24e0BjL","SHIB"),
        CoinsID("dvUj0CzDZ","AVAX"),
        CoinsID("MoTuySvg7","DAI"),
        CoinsID("x4WXHge-vvFY","WBTC"),
        CoinsID("_H5FVG9iW","UNI"),
        CoinsID("Knsels4_Ol-Ny","ATOM"),
        CoinsID("67YlI0K1b","TON"),
        CoinsID("CiixT63n3","WSTETH"),
        CoinsID("3mVx2FX_iJFp5","XMR"),
        CoinsID("hnfQfsYfeIGUQ","ETC"),
        CoinsID("aMNLwaUbY","ICP"),
        CoinsID("Pe93bIOD2","LDO"),
        CoinsID("ZlZpzOJo43mIo","BCH"),
        CoinsID("f3iaFeCKEmkaZ","XLM"),
        CoinsID("Z96jIvLU7","IMX"),
        CoinsID("ymQub4fuB","FIL"),
        CoinsID("1Uo6s62Oc","ARB"),
        CoinsID("DXwP4wF9ksbBO","HT"),
        CoinsID("jad286TjB","HBAR"),
        CoinsID("FEbS54wxo4oIl","VET"),
        CoinsID("Hm3OlynlC","TWT"),
        CoinsID("3nNpuxHJ8","FXS"),
        CoinsID("pxtKbG5rg","SAND"),
        CoinsID("HGYj5JCv5","APT"),
        CoinsID("TpHE2IShQw-sJ","ALGO"),
        CoinsID("65PHZTpmE55b","CRO"),
        CoinsID("SbWqqTui-","ENS"),
        CoinsID("tEf7-dnwV3BXS","MANA"),
        CoinsID("7C4Mh4xy1yDel","RNDR"),
        CoinsID("08CsQa-Ov","WEMIX"),
        CoinsID("DCrsaMv68","NEAR"),
        CoinsID("bauj_21eYVwso","QNT"),
        CoinsID("QUC5kVAxSoB-","MX"),
        CoinsID("JCKLgWPAF","USDP"),
        )
    }
}
